// swift-tools-version: 6.2

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Knot a Film",
    platforms: [
        .iOS("26.1"),
        .macCatalyst("26.1")
    ],
    products: [
        .iOSApplication(
            name: "Knot a Film",
            targets: ["AppModule"],
            bundleIdentifier: "duck.KnotAFilm",
            teamIdentifier: "83LSSRHW46",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cat),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .fileAccess(.downloadsFolder, mode: .readWrite)
            ],
            appCategory: .reference
        )
    ],
    targets: [
        .plugin(
            name: "MetalCompilerPlugin",
            capability: .buildTool(),
            path: "MetalCompilerPlugin"
        ),
        .executableTarget(
            name: "AppModule",
            dependencies: ["MetalShaders"],
            path: ".",
            exclude: ["MetalCompilerPlugin"],
            resources: [
                .process("MetalShaders"),
                .process("Resources/visuals"),
                .copy("Resources/mlmodels")
            ],
            swiftSettings: [
                .swiftLanguageMode(.v6),
                .interoperabilityMode(.Cxx),
                .unsafeFlags(["-cxx-interoperability-mode=default"])
            ]
        ),
        .target(
            name: "MetalShaders",
            path: "MetalShaders",
            publicHeadersPath: "include",
            cxxSettings: [],
            plugins: ["MetalCompilerPlugin"]
        )
    ],
    swiftLanguageVersions: [.version("6.2")],
    cLanguageStandard: .c18,
    cxxLanguageStandard: .cxx20
)
