// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Knot a Film",
    platforms: [
        .iOS("18.0"),
        .macCatalyst("18")
    ],
    products: [
        .iOSApplication(
            name: "Knot a Film",
            targets: ["AppModule"],
            bundleIdentifier: "duck.KnotAFilm",
            teamIdentifier: "83LSSRHW46",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .cat),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite)
            ],
            appCategory: .reference
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources/visuals"),
                .copy("Resources/mlmodels")
            ],
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals"),
                .swiftLanguageMode(.v5)
            ]
        )
    ],
    swiftLanguageVersions: [.version("6")]
)